export const providerModels: Record<string, string[]> = {
  openai: [
    "gpt-4o",
    "gpt-4o-mini",
    "gpt-4-turbo",
    "gpt-4",
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-16k",
    "text-embedding-3-small",
    "text-embedding-3-large",
    "dall-e-3",
    "dall-e-2",
    "tts-1",
    "tts-1-hd",
    "whisper-1",
  ],
  anthropic: [
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "claude-3-haiku-20240307",
    "claude-2.1",
    "claude-2.0",
    "claude-instant-1.2",
  ],
  google: [
    "gemini-1.5-pro",
    "gemini-1.5-flash",
    "gemini-1.0-pro",
    "gemini-1.0-ultra",
    "text-embedding-004",
    "text-embedding-gecko",
  ],
  deepseek: ["deepseek-coder", "deepseek-chat"],
  azure: ["gpt-4", "gpt-4-32k", "gpt-4-vision", "gpt-4-turbo", "gpt-35-turbo", "text-embedding-ada-002"],
  "openai-compatible": [],
}
